# Generated by Django 4.1.7 on 2023-04-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('click', models.CharField(max_length=50)),
            ],
        ),
    ]
